# Generated by Django 5.0.6 on 2024-06-05 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('LD', 'Lateral Direito'), ('LE', 'Lateral Esquerdo'), ('ZAG', 'Zagueiro'), ('VOL', 'Volante'), ('MC', 'Meio-Campista Central'), ('ME', 'Meia Esquerda'), ('MD', 'Meia Direita'), ('MEI', 'Meia Atacante'), ('PD', 'Ponta Direita'), ('PE', 'Ponta Esquerda'), ('ATA', 'Atacante'), ('SA', 'Segundo Atacante')], max_length=3)),
                ('potencial_min', models.PositiveIntegerField()),
                ('potencial_max', models.PositiveIntegerField()),
                ('nacionalidade', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('NLD', 'Holanda'), ('FRA', 'França'), ('BEL', 'Bélgica'), ('CHE', 'Suíça'), ('AUT', 'Áustria'), ('DNK', 'Dinamarca'), ('GBR', 'Inglaterra'), ('FIN', 'Finlândia'), ('IRL', 'Irlanda'), ('NIR', 'Irlanda do Norte'), ('NOR', 'Noruega'), ('RUS', 'Rússia'), ('SCO', 'Escócia'), ('SWE', 'Suécia'), ('HRV', 'Croácia'), ('GRC', 'Grécia'), ('PRT', 'Portugal'), ('ITA', 'Itália'), ('ESP', 'Espanha'), ('TUR', 'Turquia'), ('CZE', 'República Tcheca'), ('POL', 'Polônia'), ('ROU', 'Romênia'), ('SVK', 'Eslováquia'), ('SVN', 'Eslovênia'), ('SRB', 'Sérvia'), ('CHN', 'China'), ('JPN', 'Japão'), ('KOR', 'Coreia do Sul'), ('SAU', 'Arábia Saudita'), ('AUS', 'Austrália'), ('NZL', 'Nova Zelândia'), ('CAN', 'Canadá'), ('MEX', 'México'), ('USA', 'Estados Unidos'), ('BOL', 'Bolívia'), ('CHL', 'Chile'), ('COL', 'Colômbia'), ('ECU', 'Equador'), ('PRY', 'Paraguai'), ('PER', 'Peru'), ('URY', 'Uruguai'), ('VEN', 'Venezuela'), ('DZA', 'Argélia'), ('CMR', 'Camarões'), ('EGY', 'Egito'), ('GHA', 'Gana'), ('CIV', 'Costa do Marfim'), ('MAR', 'Marrocos'), ('NGA', 'Nigéria'), ('ZAF', 'África do Sul')], max_length=3)),
                ('temporada_subida', models.CharField(choices=[('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21'), ('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30'), ('2030/31', '2030/31')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('ING', 'Inglaterra'), ('ESP', 'Espanha'), ('ITA', 'Itália'), ('ALE', 'Alemanha'), ('FRA', 'França')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='JogadorVendido',
            fields=[
                ('jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.jogador')),
                ('valor_venda', models.PositiveIntegerField()),
                ('temporada_venda', models.CharField(choices=[('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21'), ('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30'), ('2030/31', '2030/31')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temporada', models.CharField(choices=[('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21'), ('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30'), ('2030/31', '2030/31')], max_length=7)),
                ('jogos', models.PositiveIntegerField(default=0)),
                ('gols', models.PositiveIntegerField(default=0)),
                ('assistencias', models.PositiveIntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='app.jogador')),
            ],
        ),
        migrations.AddField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.time'),
        ),
    ]
