# Generated by Django 5.0.6 on 2024-06-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='time',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
