# Generated by Django 5.0.6 on 2024-06-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_jogador_time_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NacionalidadeEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidade', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('NLD', 'Holanda'), ('FRA', 'França'), ('BEL', 'Bélgica'), ('CHE', 'Suíça'), ('AUT', 'Áustria'), ('DNK', 'Dinamarca'), ('GBR', 'Inglaterra'), ('FIN', 'Finlândia'), ('IRL', 'Irlanda'), ('NIR', 'Irlanda do Norte'), ('NOR', 'Noruega'), ('RUS', 'Rússia'), ('SCO', 'Escócia'), ('SWE', 'Suécia'), ('HRV', 'Croácia'), ('GRC', 'Grécia'), ('PRT', 'Portugal'), ('ITA', 'Itália'), ('ESP', 'Espanha'), ('TUR', 'Turquia'), ('CZE', 'República Tcheca'), ('POL', 'Polônia'), ('ROU', 'Romênia'), ('SVK', 'Eslováquia'), ('SVN', 'Eslovênia'), ('SRB', 'Sérvia'), ('CHN', 'China'), ('JPN', 'Japão'), ('KOR', 'Coreia do Sul'), ('SAU', 'Arábia Saudita'), ('AUS', 'Austrália'), ('NZL', 'Nova Zelândia'), ('CAN', 'Canadá'), ('MEX', 'México'), ('USA', 'Estados Unidos'), ('BOL', 'Bolívia'), ('CHL', 'Chile'), ('COL', 'Colômbia'), ('ECU', 'Equador'), ('PRY', 'Paraguai'), ('PER', 'Peru'), ('URY', 'Uruguai'), ('VEN', 'Venezuela'), ('DZA', 'Argélia'), ('CMR', 'Camarões'), ('EGY', 'Egito'), ('GHA', 'Gana'), ('CIV', 'Costa do Marfim'), ('MAR', 'Marrocos'), ('NGA', 'Nigéria'), ('ZAF', 'África do Sul')], max_length=3)),
                ('potencial_medio', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='JogadorVendido',
        ),
    ]
