# Generated by Django 5.0.6 on 2024-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jogador_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='nacionalidade',
            field=models.CharField(choices=[('ZAF', 'África do Sul'), ('DEU', 'Alemanha'), ('DZA', 'Argélia'), ('ARG', 'Argentina'), ('SAU', 'Arábia Saudita'), ('AUS', 'Austrália'), ('AUT', 'Áustria'), ('BEL', 'Bélgica'), ('BOL', 'Bolívia'), ('BRA', 'Brasil'), ('CAN', 'Canadá'), ('CMR', 'Camarões'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colômbia'), ('KOR', 'Coreia do Sul'), ('CIV', 'Costa do Marfim'), ('HRV', 'Croácia'), ('DNK', 'Dinamarca'), ('ECU', 'Equador'), ('EGY', 'Egito'), ('SVK', 'Eslováquia'), ('SVN', 'Eslovênia'), ('ESP', 'Espanha'), ('USA', 'Estados Unidos'), ('FIN', 'Finlândia'), ('FRA', 'França'), ('GHA', 'Gana'), ('GRC', 'Grécia'), ('NLD', 'Holanda'), ('IRL', 'Irlanda'), ('NIR', 'Irlanda do Norte'), ('ITA', 'Itália'), ('JPN', 'Japão'), ('MAR', 'Marrocos'), ('MEX', 'México'), ('NZL', 'Nova Zelândia'), ('NOR', 'Noruega'), ('PRY', 'Paraguai'), ('PER', 'Peru'), ('POL', 'Polônia'), ('PRT', 'Portugal'), ('GBR', 'Inglaterra'), ('ROU', 'Romênia'), ('RUS', 'Rússia'), ('SRB', 'Sérvia'), ('SWE', 'Suécia'), ('CHE', 'Suíça'), ('TUR', 'Turquia'), ('UKR', 'Ucrânia'), ('URY', 'Uruguai'), ('VEN', 'Venezuela')], max_length=3),
        ),
        migrations.AlterField(
            model_name='nacionalidadeestatistica',
            name='nacionalidade',
            field=models.CharField(choices=[('ZAF', 'África do Sul'), ('DEU', 'Alemanha'), ('DZA', 'Argélia'), ('ARG', 'Argentina'), ('SAU', 'Arábia Saudita'), ('AUS', 'Austrália'), ('AUT', 'Áustria'), ('BEL', 'Bélgica'), ('BOL', 'Bolívia'), ('BRA', 'Brasil'), ('CAN', 'Canadá'), ('CMR', 'Camarões'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colômbia'), ('KOR', 'Coreia do Sul'), ('CIV', 'Costa do Marfim'), ('HRV', 'Croácia'), ('DNK', 'Dinamarca'), ('ECU', 'Equador'), ('EGY', 'Egito'), ('SVK', 'Eslováquia'), ('SVN', 'Eslovênia'), ('ESP', 'Espanha'), ('USA', 'Estados Unidos'), ('FIN', 'Finlândia'), ('FRA', 'França'), ('GHA', 'Gana'), ('GRC', 'Grécia'), ('NLD', 'Holanda'), ('IRL', 'Irlanda'), ('NIR', 'Irlanda do Norte'), ('ITA', 'Itália'), ('JPN', 'Japão'), ('MAR', 'Marrocos'), ('MEX', 'México'), ('NZL', 'Nova Zelândia'), ('NOR', 'Noruega'), ('PRY', 'Paraguai'), ('PER', 'Peru'), ('POL', 'Polônia'), ('PRT', 'Portugal'), ('GBR', 'Inglaterra'), ('ROU', 'Romênia'), ('RUS', 'Rússia'), ('SRB', 'Sérvia'), ('SWE', 'Suécia'), ('CHE', 'Suíça'), ('TUR', 'Turquia'), ('UKR', 'Ucrânia'), ('URY', 'Uruguai'), ('VEN', 'Venezuela')], max_length=3),
        ),
    ]
